# Generated by Django 4.2.1 on 2024-09-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numeroPedido',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='numero',
            field=models.CharField(),
        ),
    ]
