# Generated by Django 4.2.1 on 2024-06-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_changed_my_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='fechaVencimineto',
        ),
        migrations.AddField(
            model_name='produccion',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fechaDespacho',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
